development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:334c37b39d10aa8080813ada63b42eae@pearlfish.redistogo.com:10654/
  channel_prefix: messager_rails_production
